Models/ViewModel/BlockViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Bt.Models.ViewModel
{
    public class BlockViewModel
    {
        [Column("State_Code")]
        public int StateCode { get; set; }

        [Column("District_Code")]
        public int DistrictCode { get; set; }

        [Key]
        [Column("Block_Code")]
        public int BlockCode { get; set; }

        [Column("Block_Name")]
        [StringLength(60)]
        public string BlockName { get; set; } = null!;
    }
}

Controllers/BlockController.cs
using Bt.Data;
using Bt.Models.ViewModel;
using Bt.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bt.Controllers
{
    public class BlockController : Controller
    {
        public BlockController(DhsMagacoursesContext context)
        {
            this.context=context;
        }

        public DhsMagacoursesContext context { get; }

        [HttpGet]
        public IActionResult AddBlock()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddBlock(BlockViewModel addBlock)
        {
            var block = new MBlock()
            {
                StateCode=addBlock.StateCode,
                DistrictCode=addBlock.DistrictCode,
                BlockCode=addBlock.BlockCode,
                BlockName=addBlock.BlockName,
            };
            await context.MBlocks.AddAsync(block);
            await context.SaveChangesAsync();
            return RedirectToAction("EditBlock");
        }
        [HttpGet]
        public async Task<IActionResult> EditBlock()
        {
            var block = await context.MBlocks.ToListAsync();
            return View(block);
        }

        [HttpGet]
        public async Task<IActionResult> View(int id)
        {
            var blockData = await context.MBlocks.FirstOrDefaultAsync(x => x.BlockCode==id);

            if (blockData!=null)
            {
                var viewModel = new BlockViewModel()
                {
                    StateCode=blockData.StateCode,
                    DistrictCode=blockData.DistrictCode,
                    BlockCode=blockData.BlockCode,
                    BlockName=blockData.BlockName,
                };
                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("EditBlock");
        }

        [HttpPost]
        public async Task<IActionResult> View(BlockViewModel model)
        {
            var block = await context.MBlocks.FindAsync(model.BlockCode);
            if (block!=null)
            {
                block.StateCode=model.StateCode;
                block.DistrictCode=model.DistrictCode;
                block.BlockCode=model.BlockCode;
                block.BlockName=model.BlockName;
                await context.SaveChangesAsync();
                return RedirectToAction("EditBlock");
            }
            return View("EditBlock");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(BlockViewModel model)
        {
            var block = await context.MBlocks.FindAsync(model.BlockCode);
            if (block!=null)
            {
                context.MBlocks.Remove(block);
                await context.SaveChangesAsync();
                return RedirectToAction("EditBlock");
            }
            return RedirectToAction("EditBlock");
        }

    }
}

Views/Block/AddBlock.cshtml
@model Bt.Models.ViewModel.BlockViewModel;

<form method="post" action="AddBlock" class="mt-3">
    <div class="mb-3">
        <label for="" class="form-label">State Code</label>
        <input type="number" class="form-control" asp-for="StateCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">District Code</label>
        <input type="number" class="form-control" asp-for="DistrictCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Block Code</label>
        <input type="number" class="form-control" asp-for="BlockCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Block Name</label>
        <input type="text" class="form-control" asp-for="BlockName" />
    </div>
    <button type="submit" class="btn btn-primary">Add Block</button>
    <a asp-controller="BLock" asp-action="EditBlock" class="btn btn-primary">Go Back</a>
</form>

Views/Block/EditBlock.cshtml
@model List<Bt.Models.MBlock>;
@{
}
<h1>Block</h1>
<a class="btn btn-primary" asp-area="" asp-controller="Block" asp-action="AddBlock"><i class="fa-solid fa-plus fa-xl"></i> Add Block</a>

<table class="table">
    <thead>
        <tr>
            <th>State Code</th>
            <th>District Code</th>
            <th>Block Code</th>
            <th>Block Name</th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.StateCode</td>
                <td>@item.DistrictCode</td>
                <td>@item.BlockCode</td>
                <td>@item.BlockName</td>
                <td><a class="btn btn-primary" href="View/@item.BlockCode"><i class="fa-solid fa-pen-to-square"></i> Edit</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Block/View.cshtml
@model Bt.Models.ViewModel.BlockViewModel
@{
}
<h1>Edit Block</h1>
<form method="post" action="View" class="mt-3">
    <div class="mb-3">
        <label for="" class="form-label">State Code</label>
        <input readonly class="form-control" asp-for="StateCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">District Code</label>
        <input readonly class="form-control" asp-for="DistrictCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Block Code</label>
        <input readonly class="form-control" asp-for="BlockCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Block Name</label>
        <input type="text" class="form-control" asp-for="BlockName" />
    </div>
    <button type="submit" class="btn btn-primary">Update Block</button>
    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Block">Delete Block</button>
    <a class="btn btn-primary" asp-area="" asp-controller="Block" asp-action="EditBlock"><i class="fa-solid fa-arrow-left-to-line"></i>Go Back</a>
</form>