Models/ViewModel/VillageViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Bt.Models.ViewModel
{
    public class VillageViewModel
    {
        [Column("State_Code")]
        public int StateCode { get; set; }

        [Column("District_Code")]
        public int DistrictCode { get; set; }

        [Column("Block_Code")]
        public int BlockCode { get; set; }

        [Key]
        [Column("Village_Code")]
        public int VillageCode { get; set; }

        [Column("Village_Name")]
        [StringLength(60)]
        public string VillageName { get; set; } = null!;
    }
}

Controllers/VillageController.cs
using Bt.Data;
using Bt.Models.ViewModel;
using Bt.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bt.Controllers
{
    public class VillageController : Controller
    {
        public VillageController(DhsMagacoursesContext context)
        {
            this.context=context;
        }

        public DhsMagacoursesContext context { get; }

        [HttpGet]
        public IActionResult AddVillage()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddBlock(VillageViewModel addVillage)
        {
            var village = new MVillage()
            {
                StateCode=addVillage.StateCode,
                DistrictCode=addVillage.DistrictCode,
                BlockCode=addVillage.BlockCode,
                VillageCode=addVillage.VillageCode,
                VillageName=addVillage.VillageName,
            };
            await context.MVillages.AddAsync(village);
            await context.SaveChangesAsync();
            return RedirectToAction("EditVillage");
        }
        [HttpGet]
        public async Task<IActionResult> EditVillage()
        {
            var village = await context.MVillages.ToListAsync();
            return View(village);
        }

        [HttpGet]
        public async Task<IActionResult> View(int id)
        {
            var villageData = await context.MVillages.FirstOrDefaultAsync(x => x.VillageCode==id);

            if (villageData!=null)
            {
                var viewModel = new VillageViewModel()
                {
                    StateCode=villageData.StateCode,
                    DistrictCode=villageData.DistrictCode,
                    BlockCode=villageData.BlockCode,
                    VillageCode=villageData.VillageCode,
                    VillageName=villageData.VillageName,
                };
                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("EditVillage");
        }

        [HttpPost]
        public async Task<IActionResult> View(VillageViewModel model)
        {
            var village = await context.MVillages.FindAsync(model.VillageCode);
            if (village!=null)
            {
                village.StateCode=model.StateCode;
                village.DistrictCode=model.DistrictCode;
                village.BlockCode=model.BlockCode;
                village.VillageCode=model.VillageCode;
                village.VillageName=model.VillageName;
                await context.SaveChangesAsync();
                return RedirectToAction("EditVillage");
            }
            return View("EditVillage");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(VillageViewModel model)
        {
            var village = await context.MVillages.FindAsync(model.VillageCode);
            if (village!=null)
            {
                context.MVillages.Remove(village);
                await context.SaveChangesAsync();
                return RedirectToAction("EditVillage");
            }
            return RedirectToAction("EditVillage");
        }
    }
}

Views/Village/AddVillage.cshtml
@model Bt.Models.ViewModel.VillageViewModel;

<form method="post" action="AddVillage" class="mt-3">
    <div class="mb-3">
        <label for="" class="form-label">State Code</label>
        <input type="number" class="form-control" asp-for="StateCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">District Code</label>
        <input type="number" class="form-control" asp-for="DistrictCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Village Code</label>
        <input type="number" class="form-control" asp-for="VillageCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Village Name</label>
        <input type="text" class="form-control" asp-for="VillageName" />
    </div>
    <button type="submit" class="btn btn-primary">Add Village</button>
    <a class="btn btn-primary" asp-controller="Village" asp-action="EditVillage">Go Back</a>
</form>

Views/Village/EditVillage.cshtml
@model List<Bt.Models.MVillage>;
@{
}
<h1>Village</h1>
<a class="btn btn-primary" asp-area="" asp-controller="Village" asp-action="AddVillage"><i class="fa-solid fa-plus fa-xl"></i> Add Village</a>

<hr />
<table class="table table-bordered" id="dataTableData">
    <thead>
        <tr>
            <th>State Code</th>
            <th>District Code</th>
            <th>Village Code</th>
            <th>Village Name</th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.StateCode</td>
                <td>@item.DistrictCode</td>
                <td>@item.VillageCode</td>
                <td>@item.VillageName</td>
                <td><a class="btn btn-primary" href="View/@item.VillageCode"><i class="fa-solid fa-pen-to-square"></i> Edit</a></td>
            </tr>
        }
    </tbody>
</table>
@section scripts{    
    <script src="~/js/datatable_file.js"></script>
}

Views/Village/View.cshtml
@model Bt.Models.ViewModel.VillageViewModel
@{
}
<h1>Edit Village</h1>
<form method="post" action="View" class="mt-3">
    <div class="mb-3">
        <label for="" class="form-label">State Code</label>
        <input readonly class="form-control" asp-for="StateCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">District Code</label>
        <input readonly class="form-control" asp-for="DistrictCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Block Code</label>
        <input readonly class="form-control" asp-for="BlockCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Village Code</label>
        <input readonly class="form-control" asp-for="VillageCode" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Village Name</label>
        <input type="text" class="form-control" asp-for="VillageName" />
    </div>
    <button type="submit" class="btn btn-primary">Update District</button>
    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Village">Delete Village</button>
    <a class="btn btn-primary" asp-area="" asp-controller="District" asp-action="EditDistrict"><i class="fa-solid fa-arrow-left-to-line"></i>Go Back</a>
</form>