Models/ViewModel/NationalityViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Bt.Models.ViewModel
{
    public class NationalityViewModel
    {
        public int? Nationality { get; set; }

        [Column("Nationality_Name")]
        [StringLength(20)]
        public string? NationalityName { get; set; }
    }
}

Controllers/NationalityController.cs
using Bt.Data;
using Bt.Models.ViewModel;
using Bt.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bt.Controllers
{
    public class NationalityController : Controller
    {
        public NationalityController(DhsMagacoursesContext context)
        {

            this.context=context;
        }

        public DhsMagacoursesContext context { get; }

        [HttpGet]
        public IActionResult AddNationality()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddNationality(NationalityViewModel addNationality)
        {
            var nat = new MNationality()
            {
                Nationality=addNationality.Nationality,
                NationalityName=addNationality.NationalityName,
            };
            await context.MNationalities.AddAsync(nat);
            await context.SaveChangesAsync();
            return RedirectToAction("EditNationality");
        }
        [HttpGet]
        public async Task<IActionResult> EditNationality()
        {
            var data = await context.MNationalities.ToListAsync();
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> View(int id)
        {
            var Data = await context.MNationalities.FirstOrDefaultAsync(x => x.Nationality==id);

            if (Data!=null)
            {
                var viewModel = new NationalityViewModel()
                {
                    Nationality=Data.Nationality,
                    NationalityName=Data.NationalityName,
                };
                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("Editnationality");
        }

        [HttpPost]
        public async Task<IActionResult> View(NationalityViewModel model)
        {
            var data = await context.MNationalities.FindAsync(model.Nationality);
            if (data!=null)
            {
                data.Nationality=model.Nationality;
                data.NationalityName=model.NationalityName;
                await context.SaveChangesAsync();
                return RedirectToAction("EditNationality");
            }
            return View("EditNationality");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(NationalityViewModel model)
        {
            var data = await context.MNationalities.FindAsync(model.Nationality);
            if (data!=null)
            {
                context.MNationalities.Remove(data);
                await context.SaveChangesAsync();
                return RedirectToAction("EditNationality");
            }
            return RedirectToAction("EditNationality");
        }
    }
}

Views/Nationality/AddNationality.cshtml
@model Bt.Models.ViewModel.NationalityViewModel
<a class="btn btn-primary" asp-area="" asp-controller="Nationality" asp-action="EditNationality">Go Back</a>
<form method="post" action="AddNationality" class="mt-3">
    <div class="mb-3">
        <label for="" class="form-label">Nationality Code</label>
        <input type="number" class="form-control" asp-for="Nationality" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Nationality Name</label>
        <input type="text" class="form-control" asp-for="NationalityName" />
    </div>
    <button type="submit" class="btn btn-primary">Add Nationality</button>
    <a class="btn btn-primary" asp-controller="Nationality" asp-action="EditNationality">Go Back</a>
</form>

Views/Nationality/EditNationality.cshtml
@model List<Bt.Models.MNationality>;
@{
}
<h1>Nationality</h1>

<a class="btn btn-primary" asp-area="" asp-controller="Nationality" asp-action="AddNationality"><i class="fa-solid fa-plus fa-xl"></i> Add Nationality</a>

<table class="table">
    <thead>
        <tr>
            <th>Nationality Code</th>
            <th>Nationality Description</th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Nationality</td>
                <td>@item.NationalityName</td>
                <td><a class="btn btn-primary" href="View/@item.Nationality"><i class="fa-solid fa-pen-to-square"></i> Edit</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Nationality/View.cshtml
@model Bt.Models.ViewModel.NationalityViewModel
@{
}
<a class="btn btn-primary" asp-area="" asp-controller="Nationality" asp-action="EditNationality">Go Back</a>
<h1>Edit Nationality</h1>
<form method="post" action="View" class="mt-3">
    <div class="mb-3">
        <label for="" class="form-label">Nationality Code</label>
        <input readonly class="form-control" asp-for="Nationality" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Nationality Name</label>
        <input type="text" class="form-control" asp-for="NationalityName" />
    </div>
    <button type="submit" class="btn btn-primary">Update Nationality </button>
    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Nationality">Delete Nationality</button>

</form>