Models/ViewModel/ScreeningCenterViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Bt.Models.ViewModel
{
    public class ScreeningCenterViewModel
    {
        public int? ScreeningCentre { get; set; }

        [Column("ScreeningCentre_Name")]
        [StringLength(20)]
        public string? ScreeningCentreName { get; set; }

        public int? ApplicationType { get; set; }
    }
}

Controllers/ScreeningCenterController.cs
using Bt.Data;
using Bt.Models.ViewModel;
using Bt.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bt.Controllers
{
    public class ScreeningCenterController : Controller
    {
        public ScreeningCenterController(DhsMagacoursesContext context)
        {

            this.context=context;
        }

        public DhsMagacoursesContext context { get; }

        [HttpGet]
        public IActionResult AddCenter()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddCenter(ScreeningCenterViewModel addCenter)
        {
            var center = new MScreeningCentre()
            {
                ScreeningCentre=addCenter.ScreeningCentre,
                ScreeningCentreName=addCenter.ScreeningCentreName,
                ApplicationType=addCenter.ApplicationType,
            };
            await context.MScreeningCentres.AddAsync(center);
            await context.SaveChangesAsync();
            return RedirectToAction("EditCenter");
        }
        [HttpGet]
        public async Task<IActionResult> EditCenter()
        {
            var center = await context.MScreeningCentres.ToListAsync();
            return View(center);
        }

        [HttpGet]
        public async Task<IActionResult> View(int id)
        {
            var centerData = await context.MScreeningCentres.FirstOrDefaultAsync(x => x.ScreeningCentre==id);

            if (centerData!=null)
            {
                var viewModel = new ScreeningCenterViewModel()
                {
                    ScreeningCentre=centerData.ScreeningCentre,
                    ScreeningCentreName=centerData.ScreeningCentreName,
                    ApplicationType=centerData.ApplicationType,
                };
                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("EditCenter");
        }

        [HttpPost]
        public async Task<IActionResult> View(ScreeningCenterViewModel model)
        {
            var center = await context.MScreeningCentres.FindAsync(model.ScreeningCentre);
            if (center!=null)
            {
                center.ScreeningCentre=model.ScreeningCentre;
                center.ScreeningCentreName=model.ScreeningCentreName;
                center.ApplicationType=model.ApplicationType;
                await context.SaveChangesAsync();
                return RedirectToAction("EditCenter");
            }
            return View("EditCenter");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ScreeningCenterViewModel model)
        {
            var center = await context.MScreeningCentres.FindAsync(model.ScreeningCentre);
            if (center!=null)
            {
                context.MScreeningCentres.Remove(center);
                await context.SaveChangesAsync();
                return RedirectToAction("EditCenter");
            }
            return RedirectToAction("EditCenter");
        }

    }
}

Views/ScreeningCenter/AddCenter.cshtml
@model Bt.Models.ViewModel.ScreeningCenterViewModel
<h1>Add Screening Centre</h1>
<a class="btn btn-primary" asp-area="" asp-controller="ScreeningCenter" asp-action="EditCenter"><i class="fa-solid fa-arrow-left-to-line"></i>Go Back</a>
<form method="post" action="AddCenter" class="mt-3">
    <div class="mb-3">
        <label for="" class="form-label">Screening Centre</label>
        <input type="number" class="form-control" asp-for="ScreeningCentre" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Screening Centre Name</label>
        <input type="text" class="form-control" asp-for="ScreeningCentreName" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Application Type</label>
        <input type="number" class="form-control" asp-for="ApplicationType" />
    </div>
    <button type="submit" class="btn btn-primary">Add Screening Center</button>
    <a class="btn btn-primary" asp-controller="ScreeningCenter" asp-action="EditCenter">Go Back</a>
</form>

Views/ScreeningCenter/EditCenter.cshtml
@model List<Bt.Models.MScreeningCentre>;
@{
}
<h1>Centre</h1>


<a class="btn btn-primary" asp-area="" asp-controller="ScreeningCenter" asp-action="AddCenter"><i class="fa-solid fa-plus fa-xl"></i> Add Centre</a>

<table class="table border">
    <thead>
        <tr>
            <th>Screening Centre</th>
            <th>Screening Centre Name</th>
            <th>Application Type</th>
            <th> </th>
            
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ScreeningCentre</td>
                <td>@item.ScreeningCentreName</td>
                <td>@item.ApplicationType</td>
                <td><a class="btn btn-primary" href="View/@item.ScreeningCentre"><i class="fa-solid fa-pen-to-square"></i> Edit</a></td>
            </tr>
        }
    </tbody>
</table>

Views/ScreeningCenter/View.cshtml
@model Bt.Models.ViewModel.ScreeningCenterViewModel
@{
}
<h1>Edit Screening Center</h1>
<a class="btn btn-primary" asp-area="" asp-controller="ScreeningCenter" asp-action="EditCenter"><i class="fa-solid fa-arrow-left-to-line"></i>Go Back</a>
<form method="post" action="View" class="mt-3">
    <div class="mb-3">
        <label for="" class="form-label">Screening Centre</label>
        <input readonly class="form-control" asp-for="ScreeningCentre" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Screening Centre Name</label>
        <input type="text" class="form-control" asp-for="ScreeningCentreName" />
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Application Type</label>
        <input class="form-control" asp-for="ApplicationType" />
    </div>
    <button type="submit" class="btn btn-primary">Update State</button>
    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Master">Delete Screening Center</button>

</form>